### ISSUE TITLE
My path is right but

### ISSUE THREAD

**Issue by 0x0480** [OrlovEvgeny/TinyJPG#4]
It says no such file or directory

**Comment by OrlovEvgeny** [comment]
Hi @0x0480, 
Please send a full log error.
and you OS, config.yml

**Comment by 0x0480** [comment]
That is the problem. There is no log. Just this message threw in terminal. 
Arch linux. I started with command line command.

**Comment by OrlovEvgeny** [comment]
@0x0480 Oh, sorry, CLI mode is deprecated. Please use `tinyjpg -config=/etc/tinyjpg/config.yml`

**Comment by OrlovEvgeny** [comment]
readme updated.
